<a href="https://colab.research.google.com/github/EkaterinaBoRu/Seminar8/blob/main/%D0%94%D0%97%E2%84%969.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Задание 1.** Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [42]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [6]:
len(zp)


10

In [7]:
b1 = (np.mean(zp*ks)-np.mean(zp)*np.mean(ks))/(np.mean(zp**2)-np.mean(zp)**2)
b1

2.620538882402765

In [8]:
b0 = np.mean(ks) - b1*np.mean(zp)
b0

444.1773573243596

In [9]:
y_pred = 444.1774 + 2.6205*zp
y_pred

array([535.8949, 562.0999, 942.0724, 968.2774, 548.9974, 627.6124,
       585.6844, 837.2524, 758.6374, 732.4324])

In [11]:
mse = ((ks - y_pred)**2).sum()/10
mse

6470.414221670002

In [14]:
from numpy.core.fromnumeric import reshape
x = zp.reshape(10,1)
y = ks.reshape(10,1)

In [15]:
X = np.hstack([np.ones((10,1)),x])
X

array([[  1.,  35.],
       [  1.,  45.],
       [  1., 190.],
       [  1., 200.],
       [  1.,  40.],
       [  1.,  70.],
       [  1.,  54.],
       [  1., 150.],
       [  1., 120.],
       [  1., 110.]])

In [16]:
B = np.dot(np.linalg.inv(np.dot(X.T, X)), X.T @ y)
B

array([[444.17735732],
       [  2.62053888]])

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
model = LinearRegression()

In [19]:
s= zp.reshape(-1, 1)

In [20]:
regres = model.fit(s, ks)

In [21]:
print(regres.intercept_)

444.1773573243595


In [22]:
print(regres.coef_)

[2.62053888]


In [24]:
y_pred = model.predict(s)
y_pred

array([535.89621821, 562.10160703, 942.07974498, 968.2851338 ,
       548.99891262, 627.61507909, 585.68645697, 837.25818968,
       758.64202321, 732.43663439])

**Задание 2.** Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [51]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [52]:
def mse_(B1, y=ks, x=zp, n=10):
  return np.sum((B1*x -y)**2)/10

In [53]:
alpha = 1e-6
B1 = 0.1

In [54]:
for i in range (1000):
  B1 -= alpha*(2/10)* np.sum((B1*x -y)*x)
  if i%100 ==0:
    print ('Iteration  = {i}, B1 = {B1}'.format(i=i, B1= B1))


Iteration  = 0, B1 = 0.25952808
Iteration  = 100, B1 = 5.54537842245223
Iteration  = 200, B1 = 5.868748638669329
Iteration  = 300, B1 = 5.888531320728348
Iteration  = 400, B1 = 5.8897415574471985
Iteration  = 500, B1 = 5.889815595583751
Iteration  = 600, B1 = 5.889820124983314
Iteration  = 700, B1 = 5.889820402076462
Iteration  = 800, B1 = 5.88982041902807
Iteration  = 900, B1 = 5.889820420065112


**Задание 3.** Произвести вычисления как в пункте 2, но с вычислением intercept. Учесть, что изменение коэффициентов должно производиться на каждом шаге одновременно (то есть изменение одного коэффициента не должно влиять на изменение другого во время одной итерации).

In [55]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [56]:
def mse_2(B1, B0, y=ks, x=zp, n=10):
  return np.sum((B0 + B1*x -y)**2)/10

In [57]:
alpha = 1e-6
B1 = 0.1
B0 = 0.1

In [58]:
for i in range (1000):
  B1 -= alpha*(2/10)* np.sum((B0+ B1*x -y)*x)
  B0 -= alpha*(1/10)* np.sum((B0+ B1*x -y))
  if i%100 ==0:
    print ('Iteration  = {i}, B1 = {B1}, B0 = {B0} '.format(i=i, B1= B1, B0=B0))

Iteration  = 0, B1 = 0.2595078, B0 = 0.10068348590908001 
Iteration  = 100, B1 = 5.544513288337427, B0 = 0.13086140535743157 
Iteration  = 200, B1 = 5.867729857946522, B0 = 0.1432818571297129 
Iteration  = 300, B1 = 5.887423835097829, B0 = 0.154615780711325 
Iteration  = 400, B1 = 5.888550727585718, B0 = 0.16588297096272403 
Iteration  = 500, B1 = 5.88854183618495, B0 = 0.17714581079069275 
Iteration  = 600, B1 = 5.888463468576455, B0 = 0.18840811628974455 
Iteration  = 700, B1 = 5.888380852942821, B0 = 0.1996701209048493 
Iteration  = 800, B1 = 5.888297979422949, B0 = 0.21093183892310757 
Iteration  = 900, B1 = 5.8882150921015945, B0 = 0.22219327122529242 
